---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.1.30
        k8s-1:
          ansible_host: 192.168.1.31
        k8s-2:
          ansible_host: 192.168.1.32
    worker:
      hosts:
        k8s-3:
          ansible_host: 192.168.1.33
        k8s-4:
          ansible_host: 192.168.1.34
